### ISSUE TITLE
It doesn't appear at all

### ISSUE THREAD

**Issue by nmaxcom** [nolastan/Sketch-Personas#11]
Weird thing. I've installed this plugin like the other dozen. All else are working, but not this one.

It just doesn't appear in the Plugin dropdown. I removed another persona-generator plugin just in case, but still nothing :\

**Comment by nolastan** [comment]
Thanks for raising this issue. I realized it Thursday but have been moving and no time to fix. Will do so shortly!

**Comment by nmaxcom** [comment]
Thanks. Any workaround we can do in the mean time?

**Comment by nolastan** [comment]
It should be working now, please let me know if you still run into problems.

**Comment by nmaxcom** [comment]
Now it appears in the plugin menu, but doesn't seem to work. I don't know if there's a log I can dig up to find out more.

Also (dunno if its meant to be like that), it only offers one option "personas", like that.

Thanks for the effort.

**Comment by nolastan** [comment]
Can you describe in more detail the steps you've taken and what happens when you run the plugin?

Yes there's only one option. 

You can pull up the log by running console.app and see if any errors show up when you run the plugin.

**Comment by nmaxcom** [comment]
What an idiot of me, I haven't even thought native's Console.app, thanks about that.

Just firing up Sketch I get:
`09/11/15 07:59:41,509 Sketch[18438]: Missing plugin manifest.json at URL: file:///Users/XXX/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application%20Support/com.bohemiancoding.sketch3/Plugins/Sketch-Personas-master/personas.sketchplugin/Contents/Sketch/manifest.json «Plugin Developer»`

When that happens, the plugin menu doesn't appear. Digging, I realize personas.sketchplugin is empty (??) so I re-download and put it back again.

Now it works, at least field by field. If i copy and paste the list of items that act as a variable (from gender to SSN) in the same text layer (dunno if it's meant to work like that) then it doesn't work and I get these:

```
09/11/15 08:12:41,381 Sketch[18438]: -[MOUndefined length]: unrecognized selector sent to instance 0x608000018900
09/11/15 08:12:41,383 Sketch[18438]: Exception: -[MOUndefined length]: unrecognized selector sent to instance 0x608000018900
09/11/15 08:12:41,383 personas (Sketch Plugin)[18438]: -[MOUndefined length]: unrecognized selector sent to instance 0x608000018900
```

But now I realized that it works based on the layers name and not the text content itself. For example, if the text is just "gender" but I rename the layer to SSN, I'll get a SSN. Maybe there's room for improvement there.

But thank you for your time, I might contribute myself, I think it's a very useful plugin.
