### ISSUE TITLE
Not working due to Random API changing

### ISSUE THREAD

**Issue by username1290** [nolastan/Sketch-Personas#13]
Tried:
name
location
registered

flickers, but text remains the same

**Comment by romanr** [comment]
It refreshes an nothing happens. 
It's not clear what you need to do. Crete shape and particular texts ? Then select personas from Plugins menu?
Am I doing it right? Pleas help.

**Comment by nolastan** [comment]
Seems like this is not related to Yosemite, but to the Random API changing.

Can you please try this version? If it works I will merge in the fix.

https://github.com/nolastan/Sketch-Personas/archive/fix.zip

**Comment by username1290** [comment]
Ok, I can confirm it works, thanks!   

😁 
_thumbs up_

**Comment by username1290** [comment]
btw, renamed the title to make it clear what the issue was
