### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by bomberstudios** [nolastan/Sketch-Personas#15]
Hi there,

As you probably know, `setPatternImage:` has been deprecated for a while, and it will be removed in Sketch v40. Please update your Plugin to use `setImage:` instead or it won't work in the next release :)

**Comment by nolastan** [comment]
Thanks @bomberstudios. Can you share with me how you're seeing the deprecation warnings? I'm not seeing them in `console.app` when I run the plugin.

![image](https://cloud.githubusercontent.com/assets/727778/18059417/c4b56976-6dcd-11e6-894a-68f2803cb32b.png)

**Comment by bomberstudios** [comment]
Sorry about the late reply!

I think the deprecation warnings are only showing on the Run Custom Script… window in Sketch (that's definitely _not_ the expected behaviour, I'll see if we can get that fixed : )
