### ISSUE TITLE
Shapes does not work

### ISSUE THREAD

**Issue by andyhennie** [nolastan/Sketch-Personas#8]
Seems like shapes/images does not work, and I don't get any error messages. Any ideas? See screencast: https://dl.dropboxusercontent.com/u/430406/Temp%20%5Bok%20to%20delete%5D/Gitub%20Issues/screencast%202015-08-11%2016-33-11.mp4

**Comment by nolastan** [comment]
This is a bug in RandomAPI, as it's no longer returning the image sizes. I'll reach out to them.

**Comment by nolastan** [comment]
Should be fixed now if you update the plugin https://github.com/nolastan/Sketch-Personas/pull/9
